INSERT INTO PUBLIC.AUTHOR (ID, NAME, DATE_BIRTHDAY) VALUES (1, 'Tolstoi Lev', '1828-09-09');
INSERT INTO PUBLIC.AUTHOR (ID, NAME, DATE_BIRTHDAY) VALUES (2, 'Pushkin Aleksandr', '1799-06-06');
INSERT INTO PUBLIC.GENRE (ID, NAME) VALUES (1, 'Fantasy');
INSERT INTO PUBLIC.GENRE (ID, NAME) VALUES (2, 'Action');
INSERT INTO PUBLIC.BOOK (ID, NAME, DESCRIPTION, PAGE_COUNT, GENRE_ID, AUTHOR_ID) VALUES (1, 'War and peace', 'desc', 1500, 1, 1);
INSERT INTO PUBLIC.BOOK (ID, NAME, DESCRIPTION, PAGE_COUNT, GENRE_ID, AUTHOR_ID) VALUES (2, 'Evgeny Onegin', 'desc', 500, 1, 2);
